# Generated by Django 4.1.1 on 2023-01-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobsnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animearticles',
            name='snippet',
            field=models.TextField(default='thi is some default text'),
        ),
        migrations.AlterField(
            model_name='comicsarticles',
            name='snippet',
            field=models.TextField(default='thi is some default text'),
        ),
        migrations.AlterField(
            model_name='generalarticles',
            name='snippet',
            field=models.TextField(default='thi is some default text'),
        ),
        migrations.AlterField(
            model_name='moviestvarticles',
            name='snippet',
            field=models.TextField(default='thi is some default text'),
        ),
        migrations.AlterField(
            model_name='sportsarticles',
            name='snippet',
            field=models.TextField(default='thi is some default text'),
        ),
    ]
