# Generated by Django 4.1.1 on 2023-01-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobsnews', '0002_alter_animearticles_snippet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComicsArticles',
        ),
        migrations.DeleteModel(
            name='GeneralArticles',
        ),
        migrations.DeleteModel(
            name='MoviesTVArticles',
        ),
        migrations.DeleteModel(
            name='SportsArticles',
        ),
    ]
