# Generated by Django 4.1.1 on 2023-01-09 10:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobsnews', '0003_delete_comicsarticles_delete_generalarticles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animearticles',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
